# fly.toml app configuration file generated for blogapi1200 on 2023-12-21T18:13:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blogapi1200"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="myapp_data"
  destination="/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
