GET http://localhost:3000/users/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNyYWlnIiwiaWF0IjoxNzAzMjk0MTE3LCJleHAiOjE3MDMyOTUzMTd9.tTnlW_KBNxWfpnIughEOmSMxTudFxc-tBstKHtXT4PM
###

POST http://localhost:3000/users/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNyYWlnIiwiaWF0IjoxNzAzMjk0MDY2LCJleHAiOjE3MDMyOTUyNjZ9.9uwk8Nkf00xJhK_s4ZMtesmAoWa8h7okAmac5uwXJtY
Content-Type: application/json

{"title":"title",
"text":"first Post"
}

###new token

curl -X POST -H "Content-Type:application/json" http://localhost:3000/api/login -d '{"email":"craig", "password":"123456"}'

###delete post

Delete http://localhost:3000/users/posts/657bb9e942363c0092ed838f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNAeWFob28uY29tIiwiaWF0IjoxNzAyNzYxNzc2LCJleHAiOjE3MDI3NjI5NzZ9.sF7tHPUD6QQsscUb9I-PrHzEkgo9OOXXAsi8rhCfmm8
###

PUT http://localhost:3000/users/posts/6586349ac730f3d3dfc4fed0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNyYWlnIiwiaWF0IjoxNzAzMjk0MTE3LCJleHAiOjE3MDMyOTUzMTd9.tTnlW_KBNxWfpnIughEOmSMxTudFxc-tBstKHtXT4PM
Content-Type: application/json


###delete comment
Delete http://localhost:3000/users/comments/657bba4342363c0092ed8399
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNAeWFob28uY29tIiwiaWF0IjoxNzAyNzYzNTMzLCJleHAiOjE3MDI3NjQ3MzN9.eSHnVuzuGp90HXnCeUtgWUeWGHCCjQSkG3Md9A2DMNo
###get single post
GET http://localhost:3000/users/posts/657bb9f142363c0092ed8391
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNAeWFob28uY29tIiwiaWF0IjoxNzAyNzYzMTM2LCJleHAiOjE3MDI3NjQzMzZ9.GjoNAMqDqDrWRXydd1hFAMkdVul6iuYFP7YvkzKhdB8
###get published posts
GET http://localhost:3000/api/published

###
GET http://localhost:3000/api/comments

###
Post http://localhost:3000/api/comments
Content-Type: application/json

{"name": "jack",
"text":"commenttestnew", 
"posts_id":"6586349cc730f3d3dfc4fed2"}

###

Post http://localhost:3000/api/logout

### get comments for posts

GET http://localhost:3000/api/comments/657bb9f342363c0092ed8393
